apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes_manifests/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: angular-frontend
  name: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular-frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes_manifests/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/pruebadockeryjakarta-main-datalogger-net: "true"
        io.kompose.service: angular-frontend
    spec:
      containers:
        - image: andruco29/frontendapp
          name: angular-frontend
          ports:
            - containerPort: 4200
              hostPort: 4200
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
