apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes_manifests/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: srvdb
  name: srvdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: srvdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes_manifests/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/pruebadockeryjakarta-main-datalogger-net: "true"
        io.kompose.service: srvdb
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: consultas
            - name: POSTGRES_PASSWORD
              value: QueryConSql.pwd
            - name: POSTGRES_USER
              value: consultas
            - name: TZ
              value: America/Guayaquil
          image: postgres
          name: srvdb
          ports:
            - containerPort: 5432
              hostPort: 5434
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data2
      hostname: srvdb
      restartPolicy: Always
      volumes:
        - name: pg-data2
          persistentVolumeClaim:
            claimName: pg-data2
status: {}
